"""trade migration

Revision ID: 1b8ed2d7decd
Revises: ad5c3a759631
Create Date: 2024-04-08 00:41:08.072670

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1b8ed2d7decd"
down_revision: Union[str, None] = "ad5c3a759631"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trades",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("execution_timestamp", sa.Integer(), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("qty", sa.Integer(), nullable=True),
        sa.Column("bid_order_id", sa.Integer(), nullable=True),
        sa.Column("ask_order_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ask_order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["bid_order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trades_id"), "trades", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trades_id"), table_name="trades")
    op.drop_table("trades")
    # ### end Alembic commands ###
